# Generated by Django 5.0.1 on 2025-01-30 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographrerreg',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='photographrerreg',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='photographrerreg',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='photographrerreg',
            name='pimage',
            field=models.ImageField(default='', upload_to="'media/profile/"),
        ),
        migrations.AddField(
            model_name='photographrerreg',
            name='specialization',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userreg',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userreg',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userreg',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='photographrerreg',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.CreateModel(
            name='AsiPhotographrerReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=500)),
                ('location', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=128)),
                ('specialization', models.CharField(default='', max_length=100)),
                ('pimage', models.ImageField(upload_to="'media/profile/")),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
    ]
