# Generated by Django 5.0.1 on 2025-02-02 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_photographrerreg_address_photographrerreg_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req', models.CharField(max_length=500)),
                ('reply', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.photographrerreg')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userreg')),
            ],
        ),
    ]
