# Generated by Django 5.0.1 on 2025-02-03 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='eventid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.events'),
        ),
        migrations.CreateModel(
            name='Assignassistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asisst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.asiphotographrerreg')),
                ('evid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.events')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.photographrerreg')),
            ],
        ),
    ]
