# Generated by Django 5.0.1 on 2025-02-14 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userreg'),
        ),
    ]
