# Generated by Django 5.0.6 on 2025-03-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_guest_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='pimage',
            field=models.ImageField(null=True, upload_to='', verbose_name='profile'),
        ),
    ]
