# Generated by Django 5.0.6 on 2025-03-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userreg_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignassistance',
            name='asisst',
            field=models.IntegerField(default=0),
        ),
    ]
