# Generated by Django 5.1.5 on 2025-03-27 03:47

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_assignassistance_asisst'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='submitted_to_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=app.models.photographer_directory_path),
        ),
    ]
