# Generated by Django 5.1.5 on 2025-04-01 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_events_submission_date_events_submitted_to_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.events')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.asiphotographrerreg')),
            ],
            options={
                'unique_together': {('event', 'photographer')},
            },
        ),
    ]
