# Generated by Django 5.1.5 on 2025-04-01 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_eventapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventapplication',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='message',
            field=models.TextField(default='No message provided', help_text='Message from the photographer explaining why they are interested in the event'),
        ),
        migrations.AlterField(
            model_name='eventapplication',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_applications', to='app.asiphotographrerreg'),
        ),
    ]
